name: Managely-Core
main: org.managely.ManagelyCore.ManagelyCore
version: 0.0.1a

commands:
  manage:
    description: the main configuration command for all managely modules
    usage: "Usage: /<command> <module name>"
